      - name: Smoke test API (should be 200)
        env:
          HEVY_API_KEY: ${{ secrets.HEVY_API_KEY }}
        run: |
          code=$(curl -s -o /dev/null -w '%{http_code}' \
                 -H "api-key: $HEVY_API_KEY" -H "accept: application/json" \
                 "https://api.hevyapp.com/v1/workouts?page=1&pageSize=1")
          echo "HTTP $code"
          [ "$code" -lt 400 ] || (echo "::error::Hevy API returned HTTP $code" && exit 1)
